story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.status_create, name='status_create'),
    path('delete/', views.status_delete, name='status_delete'),
]

story6/models.py
from django.db import models
from datetime import datetime, date

class Status(models.Model):
    
    status = models.CharField(max_length=300)
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.status

story6/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

story6/views.py
from django.shortcuts import render, redirect
from .models import Status
from .import forms

# def story6(request):
#     return render(request, 'story6.html')

# def status(request):
#     # status = Status.objects.all()
#     # status = Status.objects.all().order_by('date')
#     return render(request, 'story6.html', {'status': status})

def status_create(request):
    status = Status.objects.all().order_by('date')
    if request.method == 'POST':
        form = forms.StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'story6.html', {'form': form, 'status': status})

    else:
        form = forms.StatusForm()
    return render(request, 'story6.html', {'form': form, 'status':status})

def status_delete(request):
	Status.objects.all().delete()
	return redirect('story6:status_create')

story6/templates/story6.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Apa kabar?</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href = "{% static 'css/story6.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div id="header"></div>
    <div class="center">
        <p id="tag">Halo, Apa Kabar?</p>
    </div>

    <form class="create" action="{% url 'story6:status_create' %}" method="post">
        {% csrf_token %}
        <div class="form-row center">
            <div class="form-group col-sm-5" id="field">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>

        <div class="form-row center">
            <input id="add" type="submit" class="btn btn-secondary" value="Add">
        </div>
    </form>

    <div class="article">
            <div class="row">
                {% for i in status %}
                    <div class="col-sm-4 text-center">
                        <p>{{ i.status }}</p>
                        <p>{{ i.date.date }}</p>
                    </div>
                {% endfor %}
            </div>
    </div>

    <div class = 'col-md-12'>
        <div class = 'form-group'>
            <div class='text-center'>
                <a href="{% url 'story6:status_delete' %}"><button type="button" class="btn btn-secondary btn-sm">Clear</button></a>
            </div>
        </div>
    </div> 

</body>